routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Test
Route ::get( 'test' , 'TestController@test' ) -> name( 'test' );

// Auth
Route ::get( 'login' , 'Auth\LoginController@showLoginForm' ) -> name( 'login' );
Route ::post( 'login' , 'Auth\LoginController@login' );
Route ::post( 'logout' , 'Auth\LoginController@logout' ) -> name( 'logout' );

// Change locale
Route ::get( 'locale/{locale}' , 'LanguageController@changeLanguage' ) -> name( 'locale' );


/*********************************************** Admin **********************************************/

// Dashboard
Route ::get( '/panel' , 'Admin\DashboardController@dashboard' ) -> name( 'admin.dashboard' );

Route ::middleware( [ 'auth' ] ) -> prefix( 'admin' ) -> name( 'admin.' ) -> group( function()
{
    // Admin
    Route ::get( 'admins' , 'Admin\AdminController@showAdminPage' ) -> name( 'admin.page' );
    Route ::post( 'admin/list' , 'Admin\AdminController@getAdminList' ) -> name( 'admin.list' );
    Route ::post( 'admin' , 'Admin\AdminController@getAdmin' ) -> name( 'admin.get' );
    Route ::post( 'admin/edit' , 'Admin\AdminController@editAdmin' ) -> name( 'admin.edit' );
    Route ::post( 'admin/activate' , 'Admin\AdminController@activateAdmin' ) -> name( 'admin.activate' );
    Route ::post( 'admin/delete' , 'Admin\AdminController@deleteAdmin' ) -> name( 'admin.delete' );

    // Order
    Route ::get( 'orders' , 'Admin\OrderController@showOrderPage' ) -> name( 'order.page' );
    Route ::post( 'order/list' , 'Admin\OrderController@getOrderList' ) -> name( 'order.list' );
    Route ::post( 'order' , 'Admin\OrderController@getOrder' ) -> name( 'order.get' );
    Route ::post( 'order/edit' , 'Admin\OrderController@editOrder' ) -> name( 'order.edit' );
    Route ::post( 'order/activate' , 'Admin\OrderController@activateOrder' ) -> name( 'order.activate' );
    Route ::post( 'order/delete' , 'Admin\OrderController@deleteOrder' ) -> name( 'order.delete' );
    Route ::post( 'order/search' , 'Admin\OrderController@getOrderSearch' ) -> name( 'order.search' );

    // Callback
    Route ::get( 'callbacks' , 'Admin\CallbackController@showCallbackPage' ) -> name( 'callback.page' );
    Route ::post( 'callback/list' , 'Admin\CallbackController@getCallbackList' ) -> name( 'callback.list' );
    Route ::post( 'callback' , 'Admin\CallbackController@getCallback' ) -> name( 'callback.get' );
    Route ::post( 'callback/edit' , 'Admin\CallbackController@editCallback' ) -> name( 'callback.edit' );
    Route ::post( 'callback/activate' , 'Admin\CallbackController@activateCallback' ) -> name( 'callback.activate' );
    Route ::post( 'callback/delete' , 'Admin\CallbackController@deleteCallback' ) -> name( 'callback.delete' );
    Route ::post( 'callback/search' , 'Admin\CallbackController@getCallbackSearch' ) -> name( 'callback.search' );

    // Coupon
    Route ::get( 'coupons' , 'Admin\CouponController@showCouponPage' ) -> name( 'coupon.page' );
    Route ::post( 'coupon/list' , 'Admin\CouponController@getCouponList' ) -> name( 'coupon.list' );
    Route ::post( 'coupon' , 'Admin\CouponController@getCoupon' ) -> name( 'coupon.get' );
    Route ::post( 'coupon/edit' , 'Admin\CouponController@editCoupon' ) -> name( 'coupon.edit' );
    Route ::post( 'coupon/activate' , 'Admin\CouponController@activateCoupon' ) -> name( 'coupon.activate' );
    Route ::post( 'coupon/delete' , 'Admin\CouponController@deleteCoupon' ) -> name( 'coupon.delete' );
    Route ::post( 'coupon/search' , 'Admin\CouponController@getCouponSearch' ) -> name( 'coupon.search' );


    // Service
    Route ::get( 'services' , 'Admin\ServiceController@showServicePage' ) -> name( 'service.page' );
    Route ::post( 'service/list' , 'Admin\ServiceController@getServiceList' ) -> name( 'service.list' );
    Route ::post( 'service' , 'Admin\ServiceController@getService' ) -> name( 'service.get' );
    Route ::post( 'service/edit' , 'Admin\ServiceController@editService' ) -> name( 'service.edit' );
    Route ::post( 'service/activate' , 'Admin\ServiceController@activateService' ) -> name( 'service.activate' );
    Route ::post( 'service/delete' , 'Admin\ServiceController@deleteService' ) -> name( 'service.delete' );
    Route ::post( 'service/search' , 'Admin\ServiceController@getServiceSearch' ) -> name( 'service.search' );
    Route ::post( 'service/step' , 'Admin\ServiceController@getServiceStep' ) -> name( 'service.step' );

    // Service input
    Route ::get( 'service-inputs' , 'Admin\ServiceInputController@showServiceInputPage' ) -> name( 'service-input.page' );
    Route ::post( 'service-input/list' , 'Admin\ServiceInputController@getServiceInputList' ) -> name( 'service-input.list' );
    Route ::post( 'service-input' , 'Admin\ServiceInputController@getServiceInput' ) -> name( 'service-input.get' );
    Route ::post( 'service-input/edit' , 'Admin\ServiceInputController@editServiceInput' ) -> name( 'service-input.edit' );
    Route ::post( 'service-input/activate' , 'Admin\ServiceInputController@activateServiceInput' ) -> name( 'service-input.activate' );
    Route ::post( 'service-input/delete' , 'Admin\ServiceInputController@deleteServiceInput' ) -> name( 'service-input.delete' );

    // Service extra info
    Route ::get( 'service-extra-info' , 'Admin\ExtraInfoController@showExtraInfoPage' ) -> name( 'extra-info.page' );
    Route ::post( 'extra-info/list' , 'Admin\ExtraInfoController@getExtraInfoList' ) -> name( 'extra-info.list' );
    Route ::post( 'extra-info' , 'Admin\ExtraInfoController@getExtraInfo' ) -> name( 'extra-info.get' );
    Route ::post( 'extra-info/edit' , 'Admin\ExtraInfoController@editExtraInfo' ) -> name( 'extra-info.edit' );
    Route ::post( 'extra-info/activate' , 'Admin\ExtraInfoController@activateExtraInfo' ) -> name( 'extra-info.activate' );
    Route ::post( 'extra-info/delete' , 'Admin\ExtraInfoController@deleteExtraInfo' ) -> name( 'extra-info.delete' );

    // FAQ
    Route ::get( 'faq' , 'Admin\FaqController@showFaqPage' ) -> name( 'faq.page' );
    Route ::post( 'faq/list' , 'Admin\FaqController@getFaqList' ) -> name( 'faq.list' );
    Route ::post( 'faq' , 'Admin\FaqController@getFaq' ) -> name( 'faq.get' );
    Route ::post( 'faq/edit' , 'Admin\FaqController@editFaq' ) -> name( 'faq.edit' );
    Route ::post( 'faq/activate' , 'Admin\FaqController@activateFaq' ) -> name( 'faq.activate' );
    Route ::post( 'faq/delete' , 'Admin\FaqController@deleteFaq' ) -> name( 'faq.delete' );

    // Car type
    Route ::get( 'car-types' , 'Admin\CarTypeController@showCarTypePage' ) -> name( 'car-type.page' );
    Route ::post( 'car-type/list' , 'Admin\CarTypeController@getCarTypeList' ) -> name( 'car-type.list' );
    Route ::post( 'car-type' , 'Admin\CarTypeController@getCarType' ) -> name( 'car-type.get' );
    Route ::post( 'car-type/edit' , 'Admin\CarTypeController@editCarType' ) -> name( 'car-type.edit' );
    Route ::post( 'car-type/activate' , 'Admin\CarTypeController@activateCarType' ) -> name( 'car-type.activate' );
    Route ::post( 'car-type/delete' , 'Admin\CarTypeController@deleteCarType' ) -> name( 'car-type.delete' );

    // Car
    Route ::get( 'car' , 'Admin\CarController@showCarPage' ) -> name( 'car.page' );
    Route ::post( 'car/list' , 'Admin\CarController@getCarList' ) -> name( 'car.list' );
    Route ::post( 'car' , 'Admin\CarController@getCar' ) -> name( 'car.get' );
    Route ::post( 'car/edit' , 'Admin\CarController@editCar' ) -> name( 'car.edit' );
    Route ::post( 'car/activate' , 'Admin\CarController@activateCar' ) -> name( 'car.activate' );
    Route ::post( 'car/delete' , 'Admin\CarController@deleteCar' ) -> name( 'car.delete' );

    // Post ( Blog , Media )
    Route ::get( 'blog' , 'Admin\PostController@showPostPage' ) -> name( 'post-blog.page' );
    Route ::get( 'media' , 'Admin\PostController@showPostPage' ) -> name( 'post-media.page' );
    Route ::post( 'post/list' , 'Admin\PostController@getPostList' ) -> name( 'post.list' );
    Route ::post( 'post' , 'Admin\PostController@getPost' ) -> name( 'post.get' );
    Route ::post( 'post/edit' , 'Admin\PostController@editPost' ) -> name( 'post.edit' );
    Route ::post( 'post/activate' , 'Admin\PostController@activatePost' ) -> name( 'post.activate' );
    Route ::post( 'post/delete' , 'Admin\PostController@deletePost' ) -> name( 'post.delete' );

    // Campaign
    Route ::get( 'campaigns' , 'Admin\CampaignController@showCampaignPage' ) -> name( 'campaign.page' );
    Route ::post( 'campaign/list' , 'Admin\CampaignController@getCampaignList' ) -> name( 'campaign.list' );
    Route ::post( 'campaign' , 'Admin\CampaignController@getCampaign' ) -> name( 'campaign.get' );
    Route ::post( 'campaign/edit' , 'Admin\CampaignController@editCampaign' ) -> name( 'campaign.edit' );
    Route ::post( 'campaign/activate' , 'Admin\CampaignController@activateCampaign' ) -> name( 'campaign.activate' );
    Route ::post( 'campaign/delete' , 'Admin\CampaignController@deleteCampaign' ) -> name( 'campaign.delete' );

    // Econom Campaign Activity
    Route ::get( 'econom-campaign-activities' , 'Admin\EconomCampaignActivityController@showEconomCampaignActivityPage' ) -> name( 'econom-campaign-activity.page' );
    Route ::post( 'econom-campaign-activity/list' , 'Admin\EconomCampaignActivityController@getEconomCampaignActivityList' ) -> name( 'econom-campaign-activity.list' );
    Route ::post( 'econom-campaign-activity' , 'Admin\EconomCampaignActivityController@getEconomCampaignActivity' ) -> name( 'econom-campaign-activity.get' );

resources/views/admin/dashboard.blade.php
@extends('admin.index')

@section('content')

    <style>
        .not-show
        {
            display : none !important;
        }
    </style>

@endsection

resources/views/admin/extra-info.blade.php
@php
    $title = 'Service extra info';
@endphp

@extends('admin.index')

@section('title') {{ $title }} @endsection

@section('menu-header') @include('admin.menu-header') @endsection

@section('content')

    <form action="{{ route( 'admin.extra-info.list' ) }}" method="post" x-list-form="main">
        <div class="row">
            <div class="col-md-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__body">
                        <!--begin::Section-->
                        <div class="m-section">
                            <div class="m-section__content m_datatable m-datatable m-datatable--default m-datatable--loaded table-responsive">
                                <table class="table table-striped m-table m-table--head-separator-metal" x-list-table>
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Service</th>
                                            <th>Active</th>
                                            <th>Actions</th>
                                        </tr>
                                        <tr>
                                            <th></th>
                                            <th>
                                                <input type="text" class="form-control m-input m-input--air" name="title" placeholder="Title">
                                            </th>
                                            <th>
                                                <select class="form-control m-input m-input--air" name="service" x-select>
                                                    <option>All</option>
                                                    @foreach( $services as $service )
                                                        <option value="{{ $service -> id }}">{{ $service -> name }}</option>
                                                    @endforeach
                                                </select>
                                            </th>
                                            <th>
                                                <select class="form-control m-input m-input--air" name="active" x-select>
                                                    <option>All</option>
                                                    <option value="1">Active</option>
                                                    <option value="0">Inactive</option>
                                                </select>
                                            </th>
                                            <th>
                                                @if( \App\Http\Controllers\Admin\AdminController::CAN( 'service.extraInfo.add' ) )
                                                    <button type="button" class="btn m-btn btn-primary m-btn--icon m-btn--icon-only" x-add style="margin-bottom: 24px;">
                                                        <i class="la la-plus"></i>
                                                    </button>
                                                @endif
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody x-list-tbody></tbody>
                                </table>
                            </div>
                        </div>
                        <!--end::Section-->
                    </div>
                </div>
                <!--end::Portlet-->
            </div>
        </div>
    </form>

@endsection

@section('templates')

    <script type="text/template" x-tr>
        <tr x-tr-id="<%= rc.id %>">
            <td><%= rc.id %></td>
            <td><%= rc.title %></td>
            <td><%= rc.service %></td>
            <td>
                <span class="m-switch">
                    <label>
                        <input x-activate-url="{{ route('admin.extra-info.activate') }}" type="checkbox" <% if ( rc.is_active == 1 ){ %> checked="checked" <% } %> @if( ! \App\Http\Controllers\Admin\AdminController::CAN( 'service.extraInfo.activate' ) ) disabled @endif>
                        <span></span>
                    </label>
                </span>
            </td>
            <td>
                @if( \App\Http\Controllers\Admin\AdminController::CAN( 'service.extraInfo.edit' ) )
                    <button type="button" class="btn btn-sm m-btn btn-primary m-btn--icon m-btn--icon-only" x-edit-url="{{ route('admin.extra-info.get') }}">
                        <i class="m-menu__link-icon flaticon-edit"></i>
                    </button>
                @endif
                @if( \App\Http\Controllers\Admin\AdminController::CAN( 'service.extraInfo.delete' ) )
                    <button type="button" class="btn btn-sm m-btn btn-dark m-btn--icon m-btn--icon-only" x-delete-url="{{ route('admin.extra-info.delete') }}">
                        <i class="m-menu__link-icon flaticon-delete-1"></i>
                    </button>
                @endif
            </td>
        </tr>
    </script>

    <script type="text/template" x-edit-modal>
        <div class="m-portlet">
            <form action="{{ route( 'admin.extra-info.edit' ) }}" class="m-form m-form--fit m-form--label-align-right" x-edit-form>
                <input type="hidden" name="id" value="<%= rc.id %>">
                <div class="m-portlet__body">
                    <div class="row">
                        <div class="col-sm-4 form-group m-form__group upload-photo" x-photo>
                            <label>Photo</label>
                            <img src="<%= media(rc.photo) %>" x-photo-img="photo" x-photo-default="<%= media(rc.photo) %>">
                            <input type="file" name="photo" accept="image/.*" x-photo-input="photo">
                        </div>
                        <div class="col-sm-8 row">
                            <div class="col-sm-12 form-group m-form__group">
                                <label for="service">Service</label>
                                <select name="service" class="form-control m-input m-input--air" x-select x-no-submit>
                                    <option value="">Select</option>
                                    @foreach( $services as $service )
                                        <option value="{{ $service -> id }}">{{ $service -> name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-4 form-group m-form__group">
                            <label>( EN )</label>
                            <textarea rows="2" name="title_en" class="form-control m-input m-input--air" placeholder="( EN )"><%= rc.title_en %></textarea>
                        </div>
                        <div class="col-sm-4 form-group m-form__group">
                            <label>( AZ )</label>
                            <textarea rows="2" name="title_az" class="form-control m-input m-input--air" placeholder="( AZ )"><%= rc.title_az %></textarea>
                        </div>
                        <div class="col-sm-4 form-group m-form__group">
                            <label>( RU )</label>
                            <textarea rows="2" name="title_ru" class="form-control m-input m-input--air" placeholder="( RU )"><%= rc.title_ru %></textarea>
                        </div>
                    </div>
                </div>
                <div class="m-portlet__foot m-portlet__foot--fit">
                    <div class="m-form__actions">
                        <button type="submit" class="btn m-btn btn-primary pull-right"><% if( rc.id ) { %>Edit<% } else { %>Add<% } %></button>
                    </div>
                </div>
            </form>
        </div>
    </script>

@endsection

resources/views/admin/order.blade.php
@php
    $title = 'Orders';
@endphp

@extends('admin.index')

@section('title') {{ $title }} @endsection

@section('menu-header') @include('admin.menu-header') @endsection

@section('content')

    <form action="{{ route( 'admin.order.list' ) }}" method="post" x-list-form="main">
        <div class="row">
            <div class="col-md-12">
                <!--begin::Portlet-->
                <div class="m-portlet">
                    <div class="m-portlet__body">
                        <!--begin::Section-->
                        <div class="m-section">
                            <div class="m-section__content m_datatable m-datatable m-datatable--default m-datatable--loaded table-responsive">
                                <table class="table table-striped m-table m-table--head-separator-metal" x-list-table>
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Phone</th>
                                        <th>Total</th>
                                        <th>Status</th>
                                        <th>Type</th>
                                        <th>Actions</th>
                                    </tr>
                                    <tr>
                                        <th></th>
                                        <th>
                                            <input type="text" class="form-control m-input m-input--air" name="name" placeholder="Name">
                                        </th>
                                        <th>
                                            <input type="text" class="form-control m-input m-input--air" name="phone" placeholder="Phone">
                                        </th>
                                        <th>
                                            <input type="text" class="form-control m-input m-input--air" name="total" placeholder="Total">
                                        </th>
                                        <th>
                                            <select class="form-control m-input m-input--air" name="status" x-select>
                                                <option>All</option>
                                                <option value="1">Paid</option>
                                                <option value="0">Waiting</option>
                                            </select>
                                        </th>
                                        <th>
                                            <select class="form-control m-input m-input--air" name="is_order" x-select>
                                                <option>All</option>
                                                <option value="0">Calculation</option>
                                                <option value="1">Order</option>
                                            </select>
                                        </th>
                                        <th>
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody x-list-tbody></tbody>
                                </table>
                            </div>
                        </div>
                        <!--end::Section-->
                    </div>
                </div>
                <!--end::Portlet-->
            </div>
        </div>
    </form>

@endsection


@section('extra_js')

    <script>

        let k = 0;
        let x = 0;

        function addCampaignActivity( activity = {} )
        {
            activity.k = k++;

            $( '[x-order-services]' ).append( _.template( $( 'script[x-order-service]' ).html() )( activity ) );

            if( activity.inputs !== undefined && activity.inputs.length )
            {
                for( let y in activity.inputs ) {
                    addCampaignActivity1(activity.inputs[y], k);
                }
            }
        }

        function campaignActivities( data )
        {
            if( data.services !== undefined && data.services.length )
            {
                for( let i in data.services )
                {
                    console.log('service');
                    addCampaignActivity( data.services[ i ] );
                }
            }
        }

        function addCampaignActivity1( activity = {}, i = 0 )
        {
            activity.x = x++;
            $('[x-order-service-inputs-'+(i-1)+']').append(_.template($('script[x-order-service-input]').html())(activity));


        }




    </script>

@endsection


@section('templates')

    @parent()

    <script type="text/template" x-tr>
        <tr x-tr-id="<%= rc.id %>">
            <td><%= rc.id %></td>
            <td><%= rc.name %></td>
            <td><%= rc.phone %></td>
            <td>
                <% if(rc.total > 0) { %>
                <%= rc.total.toFixed(2) %> AZN
                <% } else { %>
                0 AZN
                <% } %>
            </td>
            <td>
                <% if ( rc.status == 1 ){ %>
                <span class="badge badge-success">Paid</span>
                <% } else if(rc.status == 2) { %>
                <span class="badge badge-danger">Failed</span>
                <% } else { %>
                <span class="badge badge-warning">Waiting</span>
                <% }  %>
            </td>
            <td>
                <% if ( rc.is_order == 1 ){ %>
                <span class="badge badge-success">Order</span>
                <% } else { %>
                <span class="badge badge-warning">Calculation</span>
                <% }  %>
            </td>
            <td>
                @if( \App\Http\Controllers\Admin\AdminController::CAN( 'order.edit' ) )
                    <button type="button" class="btn btn-sm m-btn btn-primary m-btn--icon m-btn--icon-only" x-edit-url="{{ route('admin.order.get') }}">
                        <i class="m-menu__link-icon flaticon-eye"></i>
                    </button>
                @endif
                @if( \App\Http\Controllers\Admin\AdminController::CAN( 'order.delete' ) )
                    <button type="button" class="btn btn-sm m-btn btn-dark m-btn--icon m-btn--icon-only" x-delete-url="{{ route('admin.order.delete') }}">
                        <i class="m-menu__link-icon flaticon-delete-1"></i>
                    </button>
                @endif
            </td>
        </tr>
    </script>

    <script type="text/template" x-edit-modal>
        <div class="m-portlet">
            <form action="{{ route( 'admin.order.edit' ) }}" class="m-form m-form--fit m-form--label-align-right" x-edit-form>
                <input type="hidden" name="id" value="<%= rc.order.id %>">
                <div class="m-portlet__body">
                    <div class="row">
                        <div class="col-sm-12 row">
                            <div class="col-sm-2 form-group m-form__group" x-step step-0 step-1>
                                <strong>Name: </strong>
                                <%= rc.order.name %>
                            </div>
                            <div class="col-sm-2 form-group m-form__group" x-step step-0 step-1>
                                <strong>Phone: </strong>
                                <%= rc.order.phone %>
                            </div>
                            <div class="col-sm-2 form-group m-form__group" x-step step-0 step-1>
                                <strong>Total: </strong>
                                <% if(rc.total > 0) { %>
                                <%= rc.total.toFixed(2) %> AZN
                                <% } else { %>
                                0 AZN
                                <% } %>
                            </div>
                            <div class="col-sm-2 form-group m-form__group" x-step step-0 step-1>
                                <strong>Type: </strong>
                                <% if ( rc.order.is_order == 1 ){ %>
                                <span class="badge badge-success">Order</span>
                                <% } else { %>
                                <span class="badge badge-danger">Calculation</span>
                                <% }  %>
                            </div>
                            <div class="col-sm-2 form-group m-form__group" x-step step-0 step-1>
                                <strong>Payment status: </strong>
                                <% if ( rc.order.status == 1 ){ %>
                                <span class="badge badge-success">Paid</span>
                                <% } else if(rc.order.status == 2) { %>
                                <span class="badge badge-danger">Failed</span>
                                <% } else { %>
                                <span class="badge badge-warning">Waiting</span>
                                <% }  %>
                            </div>
                            <div class="col-sm-2 form-group m-form__group" x-step step-0 step-1>
                                <strong>Service count: </strong>
                                <%= rc.services.length %>
                            </div>
                            <% if ( rc.order.status == 1 ){ %>
                            <div class="col-sm-2 form-group m-form__group" x-step step-0 step-1>
                                <strong>KapitalBank OrderId: </strong>
                                <%= rc.transaction.OrderId %>
                            </div>
                            <div class="col-sm-2 form-group m-form__group" x-step step-0 step-1>
                                <strong>KapitalBank SessionId: </strong>
                                <%= rc.transaction.SessionId %>
                            </div>
                            <% }  %>
                        </div>
                    </div>
                    <div class="m-portlet__body" x-order-services>
                    </div>
                </div>
            </form>
        </div>
    </script>


    <script type="text/template" x-order-service>
        <div class="m-portlet" x-order-service-id="" style="position: relative;">
            <div class="m-portlet__body">
                <h3>Xidmət #<%= rc.k+1 %></h3>
                <div class="row">
                    <div class="col-sm-12" >
                        <strong>Xidmət: </strong>
                        <%= rc.service %><% if ( rc.child_service ){ %> - <%= rc.child_service %><% }  %>
                    </div>
                    <% if ( rc.inputs.length ){ %><div class="m-portlet__body row col-sm-12" x-order-service-inputs-<%= rc.k %>></div><% }  %>
            </div>
        </div>
        </div>
    </script>

    <script type="text/template" x-order-service-input>
        <div class="col-sm-3" >
            <strong><%= rc.name %>: </strong>
            <%= rc.value %>
        </div>
    </script>
@endsection