routes/web.php
    Route ::post( 'econom-campaign-activity/activate' , 'Admin\EconomCampaignActivityController@activateEconomCampaignActivity' ) -> name( 'econom-campaign-activity.activate' );
    Route ::post( 'econom-campaign-activity/delete' , 'Admin\EconomCampaignActivityController@deleteEconomCampaignActivity' ) -> name( 'econom-campaign-activity.delete' );

    // Econom Campaign
    Route ::get( 'econom-campaigns' , 'Admin\EconomCampaignController@showEconomCampaignPage' ) -> name( 'econom-campaign.page' );
    Route ::post( 'econom-campaign/list' , 'Admin\EconomCampaignController@getEconomCampaignList' ) -> name( 'econom-campaign.list' );
    Route ::post( 'econom-campaign' , 'Admin\EconomCampaignController@getEconomCampaign' ) -> name( 'econom-campaign.get' );
    Route ::post( 'econom-campaign/edit' , 'Admin\EconomCampaignController@editEconomCampaign' ) -> name( 'econom-campaign.edit' );
    Route ::post( 'econom-campaign/activate' , 'Admin\EconomCampaignController@activateEconomCampaign' ) -> name( 'econom-campaign.activate' );
    Route ::post( 'econom-campaign/delete' , 'Admin\EconomCampaignController@deleteEconomCampaignActivity' ) -> name( 'econom-campaign.delete' );
    Route ::post( 'econom-campaign/includes' , 'Admin\EconomCampaignController@getEconomCampaignIncludes' ) -> name( 'econom-campaign.includes' );

    // Hourly Campaign Activity
    Route ::get( 'hourly-campaign-activities' , 'Admin\HourlyCampaignActivityController@showHourlyCampaignActivityPage' ) -> name( 'hourly-campaign-activity.page' );
    Route ::post( 'hourly-campaign-activity/list' , 'Admin\HourlyCampaignActivityController@getHourlyCampaignActivityList' ) -> name( 'hourly-campaign-activity.list' );
    Route ::post( 'hourly-campaign-activity' , 'Admin\HourlyCampaignActivityController@getHourlyCampaignActivity' ) -> name( 'hourly-campaign-activity.get' );
    Route ::post( 'hourly-campaign-activity/edit' , 'Admin\HourlyCampaignActivityController@editHourlyCampaignActivity' ) -> name( 'hourly-campaign-activity.edit' );
    Route ::post( 'hourly-campaign-activity/activate' , 'Admin\HourlyCampaignActivityController@activateHourlyCampaignActivity' ) -> name( 'hourly-campaign-activity.activate' );
    Route ::post( 'hourly-campaign-activity/delete' , 'Admin\HourlyCampaignActivityController@deleteHourlyCampaignActivity' ) -> name( 'hourly-campaign-activity.delete' );

    // Hourly Campaign
    Route ::get( 'hourly-campaigns' , 'Admin\HourlyCampaignController@showHourlyCampaignPage' ) -> name( 'hourly-campaign.page' );
    Route ::post( 'hourly-campaign/list' , 'Admin\HourlyCampaignController@getHourlyCampaignList' ) -> name( 'hourly-campaign.list' );
    Route ::post( 'hourly-campaign' , 'Admin\HourlyCampaignController@getHourlyCampaign' ) -> name( 'hourly-campaign.get' );
    Route ::post( 'hourly-campaign/edit' , 'Admin\HourlyCampaignController@editHourlyCampaign' ) -> name( 'hourly-campaign.edit' );
    Route ::post( 'hourly-campaign/activate' , 'Admin\HourlyCampaignController@activateHourlyCampaign' ) -> name( 'hourly-campaign.activate' );
    Route ::post( 'hourly-campaign/delete' , 'Admin\HourlyCampaignController@deleteHourlyCampaignActivity' ) -> name( 'hourly-campaign.delete' );
    Route ::post( 'hourly-campaign/includes' , 'Admin\HourlyCampaignController@getHourlyCampaignIncludes' ) -> name( 'hourly-campaign.includes' );

    // Vacancy
    Route ::get( 'vacancies' , 'Admin\VacancyController@showVacancyPage' ) -> name( 'vacancy.page' );
    Route ::post( 'vacancy/list' , 'Admin\VacancyController@getVacancyList' ) -> name( 'vacancy.list' );
    Route ::post( 'vacancy' , 'Admin\VacancyController@getVacancy' ) -> name( 'vacancy.get' );
    Route ::post( 'vacancy/edit' , 'Admin\VacancyController@editVacancy' ) -> name( 'vacancy.edit' );
    Route ::post( 'vacancy/activate' , 'Admin\VacancyController@activateVacancy' ) -> name( 'vacancy.activate' );
    Route ::post( 'vacancy/delete' , 'Admin\VacancyController@deleteVacancy' ) -> name( 'vacancy.delete' );

    // Employee
    Route ::get( 'employees' , 'Admin\EmployeeController@showEmployeePage' ) -> name( 'employee.page' );
    Route ::post( 'employee/list' , 'Admin\EmployeeController@getEmployeeList' ) -> name( 'employee.list' );
    Route ::post( 'employee' , 'Admin\EmployeeController@getEmployee' ) -> name( 'employee.get' );
    Route ::post( 'employee/edit' , 'Admin\EmployeeController@editEmployee' ) -> name( 'employee.edit' );
    Route ::post( 'employee/activate' , 'Admin\EmployeeController@activateEmployee' ) -> name( 'employee.activate' );
    Route ::post( 'employee/delete' , 'Admin\EmployeeController@deleteEmployee' ) -> name( 'employee.delete' );

    // Slider
    Route ::get( 'sliders' , 'Admin\SliderController@showSliderPage' ) -> name( 'slider.page' );
    Route ::post( 'slider/list' , 'Admin\SliderController@getSliderList' ) -> name( 'slider.list' );
    Route ::post( 'slider' , 'Admin\SliderController@getSlider' ) -> name( 'slider.get' );
    Route ::post( 'slider/edit' , 'Admin\SliderController@editSlider' ) -> name( 'slider.edit' );
    Route ::post( 'slider/activate' , 'Admin\SliderController@activateSlider' ) -> name( 'slider.activate' );
    Route ::post( 'slider/delete' , 'Admin\SliderController@deleteSlider' ) -> name( 'slider.delete' );

    // Site info
    Route ::get( 'site-info' , 'Admin\SiteController@showSitePage' ) -> name( 'site.page' );
    Route ::post( 'edit-site-info' , 'Admin\SiteController@editSiteInfo' ) -> name( 'site.edit' );

    // Mission
    Route ::get( 'missions' , 'Admin\MissionController@showMissionPage' ) -> name( 'mission.page' );
    Route ::post( 'mission/list' , 'Admin\MissionController@getMissionList' ) -> name( 'mission.list' );
    Route ::post( 'mission' , 'Admin\MissionController@getMission' ) -> name( 'mission.get' );
    Route ::post( 'mission/edit' , 'Admin\MissionController@editMission' ) -> name( 'mission.edit' );
    Route ::post( 'mission/activate' , 'Admin\MissionController@activateMission' ) -> name( 'mission.activate' );
    Route ::post( 'mission/delete' , 'Admin\MissionController@deleteMission' ) -> name( 'mission.delete' );

    // Settings
    Route ::get( 'settings' , 'Admin\AdminController@showSettings' ) -> name( 'settings' );
    Route ::post( 'change-password' , 'Admin\AdminController@changePassword' ) -> name( 'changePassword' );
} )
;


/**************************************** Site pages with locale ***************************************/

// 404
Route ::get( '404' , 'Site\SiteController@_404' ) -> name( '_404' );

Route ::middleware( [ 'language' ] ) -> prefix( '{locale?}' ) -> name( 'site.' ) -> group( function()
{

    //KapitalBank Callback
    Route ::post( 'order_approved' , 'Site\OrderController@order_approved' ) -> name( 'order_approved' );
    Route ::post( 'order_canceled' , 'Site\OrderController@order_canceled' ) -> name( 'order_canceled' );
    Route ::post( 'order_declined' , 'Site\OrderController@order_declined' ) -> name( 'order_declined' );

    // Home
    Route ::get( '/' , 'Site\SiteController@homepage' ) -> name( 'home' );

    // About
    Route ::get( 'about' , 'Site\SiteController@about' ) -> name( 'about' );

    // Contact
    Route ::get( 'contact' , 'Site\SiteController@contact' ) -> name( 'contact' );

    // Services
    Route ::get( 'services' , 'Site\ServiceController@services' ) -> name( 'services' );
    Route ::get( 'service/{id}' , 'Site\ServiceController@service' ) -> name( 'service' );

    // Blog
    Route ::get( 'blog/{service?}' , 'Site\PostController@blogPage' ) -> name( 'blog.page' );
    Route ::post( 'blog-posts' , 'Site\PostController@getBlogPostList' ) -> name( 'blog-post.list' );
    Route ::get( 'blog-post/{id?}' , 'Site\PostController@blogPostPage' ) -> name( 'blog-post.page' );

    // We at media
    Route ::get( 'media' , 'Site\PostController@mediaPage' ) -> name( 'media.page' );
    Route ::post( 'media-posts' , 'Site\PostController@getMediaPostList' ) -> name( 'media-post.list' );
    Route ::get( 'media-post/{id?}' , 'Site\PostController@mediaPostPage' ) -> name( 'media-post.page' );

    // Car
    Route ::get( 'cars/{id?}' , 'Site\CarController@carsPage' ) -> name( 'cars.page' );
    Route ::get( 'car/{id?}' , 'Site\CarController@carPage' ) -> name( 'car.page' );

    // FAQ
    Route ::get( 'faq' , 'Site\FaqController@faqPage' ) -> name( 'faq.page' );

    // Career
    Route ::get( 'career' , 'Site\VacancyController@careerPage' ) -> name( 'career.page' );
    Route ::get( 'vacancy/{id}' , 'Site\VacancyController@vacancyPage' ) -> name( 'vacancy.page' );

    // Team
    Route ::get( 'team' , 'Site\EmployeeController@teamPage' ) -> name( 'team.page' );

    // Campaign
    Route ::get( 'campaigns' , 'Site\CampaignController@campaignsPage' ) -> name( 'campaigns.page' );
    Route ::post( 'campaigns' , 'Site\CampaignController@getCampaignList' ) -> name( 'campaign.list' );
    Route ::get( 'campaign/{id}' , 'Site\CampaignController@campaignPage' ) -> name( 'campaign.page' );
    Route ::post( 'campaigns/sendPhone' , 'Site\CampaignController@sendPhone' ) -> name( 'campaigns.sendPhone' );

    // Gallery
    Route ::get( 'gallery' , 'Site\GalleryController@gallery' ) -> name( 'gallery.page' );
    //Route ::get( 'gallery' , 'Site\GalleryController@galleryPage' ) -> name( 'gallery.page' );
    Route ::post( 'gallery' , 'Site\GalleryController@getImageList' ) -> name( 'gallery.list' );

    // Order
    Route ::get( 'order' , 'Site\OrderController@orderPage' ) -> name( 'order.page' );
} )
;


/******************************************** Site actions *******************************************/

//Callback time
Route ::post( 'callback' , 'Site\SiteController@callback' ) -> name( 'callback' );

//Subscribe
Route ::post( 'subscribe' , 'Site\SiteController@subscribe' ) -> name( 'subscribe' );

// Apply
Route ::post( 'apply' , 'Site\SiteController@apply' ) -> name( 'apply' );

// Apply to vacancy

app/Http/Controllers/Site/CampaignController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Models\Campaign;
use App\Models\EconomCampaign;
use App\Models\EconomCampaignActivity;
use App\Models\EconomCampaignInclude;
use App\Models\HourlyCampaign;
use App\Models\HourlyCampaignActivity;
use App\Models\HourlyCampaignInclude;
use App\Models\HourlyCampaignAlert;
use App\Models\Service;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;
use App\Models\Coupon;
use Illuminate\Support\Facades\Session;

class CampaignController extends Controller
{
    public function campaignsPage( Request $request )
    {
        try
        {
            $economCampaigns = DB ::table( EconomCampaign::TABLE . ' AS c' )
                -> join( Service::TABLE . ' AS s' , 'c.service_id' , 's.id' )
                -> leftJoin( EconomCampaignInclude::TABLE . ' AS i' , 'c.id' , 'i.campaign_id' )
                -> where( 'c.is_deleted' , 0 ) -> where( 'c.is_active' , 1 )
                -> where( 's.is_deleted' , 0 ) -> where( 's.is_active' , 1 )
                -> groupBy( 'c.id' , self ::LANG_PARAM( 'title' , '' , false ) , self ::LANG_PARAM( 'individual_text' , '' , false ) , self ::LANG_PARAM( 'corporate_text' , '' , false ) , 'c.price' , 'service_id' , 'c.photo' )
                -> select( 'c.id' , self ::LANG_PARAM( 'title' ) , self ::LANG_PARAM( 'individual_text' ) , self ::LANG_PARAM( 'corporate_text' ) , 'c.price' , 'service_id' , DB ::raw( "GROUP_CONCAT( i.activity_id SEPARATOR ',' ) AS includes" ) , 'c.photo' )
                -> get()
            ;

            $economCampaignActivities = DB ::table( EconomCampaignActivity::TABLE . ' AS a' )
                -> join( Service::TABLE . ' AS s' , 'a.service_id' , 's.id' )
                -> where( 'a.is_deleted' , 0 ) -> where( 'a.is_active' , 1 )
                -> where( 's.is_deleted' , 0 ) -> where( 's.is_active' , 1 )
                -> select( 'a.id' , self ::LANG_PARAM( 'name' , 'a' ) , 'service_id' )
                -> get()
            ;

            foreach( $economCampaigns as $key => $economCampaign )
            {
                foreach( $economCampaignActivities as $economCampaignActivity )
                {
                    if( $economCampaign -> service_id == $economCampaignActivity -> service_id )
                    {
                        $economCampaigns[ $key ] -> activities[] = (object)[
                            'id'       => $economCampaignActivity -> id ,
                            'name'     => $economCampaignActivity -> name ,
                            'included' => in_array( $economCampaignActivity -> id , explode( ',' , $economCampaign -> includes ) )
                        ];
                    }
                }
            }


            $hourlyCampaigns = DB ::table( HourlyCampaign::TABLE . ' AS c' )
                -> join( Service::TABLE . ' AS s' , 'c.service_id' , 's.id' )
                -> leftJoin( HourlyCampaignInclude::TABLE . ' AS i' , 'c.id' , 'i.campaign_id' )
                -> where( 'c.is_deleted' , 0 ) -> where( 'c.is_active' , 1 )
                -> where( 's.is_deleted' , 0 ) -> where( 's.is_active' , 1 )
                -> groupBy( 'c.id' , self ::LANG_PARAM( 'individual_text' , '' , false ) , self ::LANG_PARAM( 'corporate_text' , '' , false ) , 'hour' , 'day_1_price' , 'day_2_price' , 'day_3_price' , 'service_id' )
                -> select( 'c.id' , self ::LANG_PARAM( 'individual_text' ) , self ::LANG_PARAM( 'corporate_text' ) , 'hour' , 'day_1_price' , 'day_2_price' , 'day_3_price' , 'service_id' , DB ::raw( "GROUP_CONCAT( i.activity_id SEPARATOR ',' ) AS includes" ) )
                -> get()
            ;

            $hourlyCampaignActivities = DB ::table( HourlyCampaignActivity::TABLE . ' AS a' )
                -> join( Service::TABLE . ' AS s' , 'a.service_id' , 's.id' )
                -> where( 'a.is_deleted' , 0 ) -> where( 'a.is_active' , 1 )
                -> where( 's.is_deleted' , 0 ) -> where( 's.is_active' , 1 )
                -> select( 'a.id' , self ::LANG_PARAM( 'name' , 'a' ) , 'service_id' )
                -> get()
            ;

            foreach( $hourlyCampaigns as $key => $hourlyCampaign )
            {
                foreach( $hourlyCampaignActivities as $hourlyCampaignActivity )
                {
                    if( $hourlyCampaign -> service_id == $hourlyCampaignActivity -> service_id )
                    {
                        $hourlyCampaigns[ $key ] -> activities[] = (object)[
                            'id'       => $hourlyCampaignActivity -> id ,
                            'name'     => $hourlyCampaignActivity -> name ,
                            'included' => in_array( $hourlyCampaignActivity -> id , explode( ',' , $hourlyCampaign -> includes ) )
                        ];

                        $hourlyCampaigns[ $key ] -> alerts = DB ::table( HourlyCampaignAlert::TABLE )
                            -> where( 'campaign_id' , $hourlyCampaign -> id )
                            -> select( 'id' , self ::LANG_PARAM( 'text' ) )
                            -> get()
                        ;
                    }
                }
            }

            return view( 'site.campaign.campaigns' , compact( [ 'economCampaigns' , 'hourlyCampaigns' ] ) );
        }
        catch( \Exception $exception )
        {
            return $this -> getException( $exception );
        }
    }


    public function getCampaignList( Request $request )
    {
        try
        {
            $SELECT = ' SELECT c.id , ' . self ::LANG_PARAM( 'title' ) . ' , ' . self ::LANG_PARAM( 'individual_headline' , 'c' ) . ' , ' . self ::LANG_PARAM( 'corporate_headline' , 'c' ) . ' , input , c.photo ';

            $FROM = ' FROM ' . Campaign::TABLE . ' c JOIN ' . Service::TABLE . ' s ON c.service_id = s.id ';

            $WHERE = ' WHERE c.is_deleted = 0 AND c.is_active = 1 AND s.is_deleted = 0 AND s.is_active = 1 ';

            $filter = [
                'search' => [ 'type' => 'search' , 'db' => [ self ::LANG_PARAM( 'title' ) ] ]
            ];

            $campaigns = $this -> configureList( $request , $SELECT , $FROM , $WHERE , $filter , [ 'default' => 'c.start_date' ] );

            //var_dump(Session::get('message'));die();
            foreach( $campaigns[ 'data' ] as $key => $campaign )
            {
                $campaigns[ 'data' ][ $key ] -> photo = $this -> avatar( $campaign -> photo , 'campaign' );
                $campaigns[ 'data' ][ $key ] -> message = session('message');
            }
            Session::forget('message');
            return response() -> json( array_merge( [ 'status' => 'success' ] , $campaigns ) );
        }
        catch( \Exception $exception )
        {
            return $this -> getException( $exception );
        }
    }


    public function campaignPage( $locale , $id = 0 )
    {
        try
        {
            $id = $this -> validator -> validateId( $id );

            $campaign = '';

            if( ! ( $campaign && isset( $campaign -> title ) ) ) return $this -> _404();

            $campaigns = [];

            return view( 'site.campaign.campaign' , compact( [ 'campaign' , 'campaigns' ] ) );
        }
        catch( \Exception $exception )
        {
            return $this -> getException( $exception );
        }
    }

    public function sendPhone(Request $request) {
        try
        {
            $validatedData = $request->validate([
                'phone' => 'required'
            ]);

            Session::put('message', 'Sizinlə tezliklə əlaqə saxlanılacaq');


            Coupon::insert(['phone' => $request->request->get('phone')]);
            return redirect(route('site.campaigns.page'));
        }
        catch( \Exception $exception )
        {
            return $this -> getException( $exception );
        }
    }
}

resources/views/site/vacancy/career.blade.php
@extends('site.index')

@section('content')

    <main>
        <section class="page-header career-header" style="background-image: url({{ \App\Http\Controllers\Site\SiteController::BACKGROUND('career') }})">
            <div class="page-header__over"></div>
            <div class="page-header__title">
                <h1 class="title">{{ __('message.Career') }}</h1>
                <div class="title-after">
                    <div class="title-after--item"></div>
                    <div class="title-after--item"></div>
                    <div class="title-after--item"></div>
                    <div class="title-after--item"></div>
                    <div class="title-after--item"></div>
                </div>
            </div>
        </section>
        <nav class="breadcrumb container mb-0 py-0">
            <a class="breadcrumb-item" href="{{ route('site.home') }}">{{ __('message.Homepage') }}</a>
            <a class="breadcrumb-item active" aria-current="page">{{ __('message.Career') }}</a>
        </nav>
        <section class="vacancies">
            <div class="container vacancies-container">
                <h6>{{ __('message.You_can_take_advantage_of_open_vacancies_to_join_our_team') }}</h6>
                @foreach( $vacancies as $vacancy )
                    <div class="vacancies-item">
                        <img src="{{ \App\Http\Controllers\Controller::_AVATAR( $vacancy -> photo , 'vacancy' ) }}" alt="">
                        <div class="vacancies-item__text">
                            <h6>{{ $vacancy -> title }}</h6>
                            <p>{{ $vacancy -> text }}</p>
                        </div>
                        <a class="btn" href="{{ route( 'site.vacancy.page' , [ 'id' => $vacancy -> id ] ) }}">{{ __('message.READ_MORE') }}</a>
                    </div>
                @endforeach
            </div>
        </section>
        @include('site.subscribe')
    </main>

@endsection

resources/views/site/vacancy/vacancy.blade.php
@extends('site.index')

@section('title') {{ $vacancy -> title }} @endsection

@section('og')
    <meta property="og:title" content="{{ $vacancy -> title }}">
    <meta property="og:image" content="{{ media( 'vacancy/' . $vacancy -> og_image ) }}">
@endsection

@section('content')

    <main>
        <section class="page-header career-header" style="background-image: url( {{ media( 'vacancy/' . $vacancy -> background ) }} ) !important;">
            <div class="page-header__over"></div>
            <div class="page-header__title">
                <h1 class="title">{{ $vacancy -> title }}</h1>
                <div class="title-after">
                    <div class="title-after--item"></div>
                    <div class="title-after--item"></div>
                    <div class="title-after--item"></div>
                    <div class="title-after--item"></div>
                    <div class="title-after--item"></div>
                </div>
            </div>
        </section>
        <nav class="breadcrumb container mb-0 py-0">
            <a class="breadcrumb-item" href="{{ route('site.home') }}">{{ __('message.Homepage') }}</a>
            <a class="breadcrumb-item" href="{{ route('site.career.page') }}">{{ __('message.Career') }}</a>
            <a class="breadcrumb-item active" aria-current="page">{{ $vacancy -> title }}</a>
        </nav>
        <section class="vacancies-info">
            <div class="container">
                <h2>{{ __('message.About_vacancy') }}</h2>
                @foreach( $vacancy -> details as $detail )
                    <p><img src="{{ asset('site/img/check.png') }}" alt="">{{ $detail -> name }}</p>
                @endforeach

                <h2 class="mt-5">{{ __('message.Vacancy_requirements') }}</h2>
                @foreach( $vacancy -> requirements as $requirement )
                    <p><img src="{{ asset('site/img/check.png') }}" alt="">{{ $requirement -> name }}</p>
                @endforeach

                <h2>{{ __('message.Note') }}</h2>
                <p>{!! $vacancy -> note !!}</p>

                <button type="button" class="btn" data-toggle="modal" data-target=".online-apply">{{ __('message.APPLY_ONLINE') }}</button>
                <div class="modal fade online-apply" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <button type="button" class="close" data-dismiss="modal">
                            <img src="{{ asset('site/img/cancel.png') }}" alt="">
                        </button>
                        <div class="modal-content">
                            <h3>{{ $vacancy -> title }}</h3>
                            <p>{{ __('message.APPLY_ONLINE') }}</p>
                            <form x-edit-form x-target="afterApply" method="post" action="{{ route('apply-to-vacancy') }}">
                                <input type="hidden" name="vacancy" value="{{ $vacancy -> id }}">
                                <div class="form-group">
                                    <label for="inputName">{{ __('message.NameSurname') }} *</label>
                                    <input type="text" class="form-control" id="inputName" name="name">
                                </div>
                                <div class="form-group">
                                    <label for="inputEmail">{{ __('message.Email') }} *</label>
                                    <input type="text" class="form-control" id="inputEmail" name="email">
                                </div>
                                <div class="form-group">
                                    <label for="inputMobile">{{ __('message.Phone') }} *</label>
                                    <input type="text" class="form-control" id="inputMobile" name="phone">
                                </div>
                                <div class="form-group">
                                    <label for="inputCv">{{ __('message.Upload_CV') }} *</label>
                                    <label style=" width: 100%;
                                height: 38px;
                                border-radius: 10px;
                                border: 1px solid #efefef;
                                background-color: #f6f7f7;
                                display: inline-block;
                                padding: 6px 12px;
            " for="file-upload" class="form-group__label">
                                        <span></span>
                                        <img src="{{ asset('site/img/download.png') }}">
                                    </label>
                                    <input id="file-upload" class="d-none" name="cv" type="file" accept=".doc , .docx , .pdf">
                                </div>
                                <button type="submit" class="btn ">{{ __('message.Apply') }}</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div id="apply-success-modal" class="modal fade modal-service">
                    <div class="modal-dialog modal-service__dialog">
                        <div class="modal-content modal-service__content">
                            <div class="modal-header modal-service__header">
                                <h6>{{ __('message.Thank_you_for_applying') }}</h6>
                            </div>
                            <div class="modal-close" data-dismiss="modal">
                                <i class="fa fa-times"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="vacancies">
            <div class="container vacancies-container">
                <h6>{{ __('message.You_can_take_advantage_of_open_vacancies_to_join_our_team') }}</h6>
                @foreach( $vacancies as $vacancy )
                    <div class="vacancies-item">
                        <img src="{{ \App\Http\Controllers\Controller::_AVATAR( $vacancy -> photo , 'vacancy'  ) }}" alt="">
                        <div class="vacancies-item__text">
                            <h6>{{ $vacancy -> title }}</h6>
                            <p>{{ $vacancy -> text }}</p>
                        </div>
                        <a class="btn" href="{{ route( 'site.vacancy.page' , [ 'id' => $vacancy -> id ] ) }}">{{ __('message.READ_MORE') }}</a>
                    </div>
                @endforeach
            </div>
        </section>
    </main>

@endsection


@section('extra_js')

    <script>
        function afterApply( response )
        {
            $( '[x-target="afterApply"]' ).trigger( 'reset' );

            $( '[x-target="afterApply"]' ).find( '.form-group__label' ).html( '<span></span><img src="{{ asset('site/img/download.png') }}">' );

            $( '.online-apply' ).modal( 'hide' );

            $( '#apply-success-modal' ).modal( 'show' );
        }

    </script>

@endsection